apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: yh-build-task
  namespace: class-2
spec:
  params:
    - name: app-name
      type: string
  steps:
    - name: build
      image: alpine:3.20
      script: |
        #!/bin/sh
        echo "Building $(params.app-name)"

