apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: yh-clone-and-build
  namespace: class-2
spec:
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
      default: main
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-source
      taskRef:
        # kind: ClusterTask 를 삭제하거나 아래처럼 name만 남기세요.
        name: git-clone 
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: shared-workspace

