apiVersion: v1
kind: Secret
metadata:
  name: harbor-pull-secret
  namespace: class-2
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "amdp-registry.skala-ai.com": {
          "username": "robot$skala26a-ai2",
          "password": "Va9M8WvbaoPa4oxpqFHMH4TH0h02GbTH",
          "auth": "$(echo -n 'robot$skala26a-ai2:Va9M8WvbaoPa4oxpqFHMH4TH0h02GbTH' | base64)"
        }
      }
    }
