apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sk052-1-pvc  # 언더바(_)는 쿠버네티스 리소스 이름에 사용할 수 없어 하이픈(-)으로 대체했습니다.
  namespace: class-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3

