apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk052-devops-app
  namespace: skala3-ai2
  labels:
    app: sk052-devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sk052-devops-app
  template:
    metadata:
      labels:
        app: sk052-devops-app
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: sk052-devops-app
          image: __IMAGE__
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
