apiVersion: v1
kind: Service
metadata:
  name: sk052-devops-app
  namespace: skala3-ai2
spec:
  selector:
    app: sk052-devops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
